# The fields in this section used by the jekyll-seo-tag plugin (and may also appear on the webpage).
title: Parcel and Freight Shipping for SAP
tagline: A blog platform for discussing SAP shipping software and the small parcel courier express industry"
description: > # this means to ignore newlines until "show_excerpts:"
  A blog dedicated to parcel carriers, commercial invoices, bills of lading &
  freight forwarding. Sound interesting?  How about web services, XML
  templates, APIs & HTTP REST communication? Let's go deep and compare German,
  Belgian & French DPD WSDLs. Activate express shipping in SAP and print FedEx
  & UPS shipping labels. Now print thousands of labels every day for sites
  located around the world. Automate Purolator and DHL customer return labels.
  This is amazing technology. This is what I write about.

author:
  name:              Josh Riff
  email:             josh.riff@blueharbors.com
  twitter:           jmriff
logo:                /assets/profilePics/profilePic03.jpg

social:
   name: Josh Riff
   links:
      - https://twitter.com/jmriff
      - https://www.linkedin.com/in/joshriff

# These settings control the behavior of the webpage.
show_excerpts:       false  # show post excerpts on the homepage if set to TRUE
future:              false  # publish future dated posts if set to TRUE
url:                 "https://jmriff.github.io"
baseurl:             "/parcelShippingNews"
permalink:           pretty

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: jmriff
    # github:  jekyll
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: joshriff
    # pinterest: jekyll
    # youtube: jekyll
    youtube_channel: UC-fI_Qe43gdJoHAXHYb7NnQ
    youtube_channel_name: "Express Shipping Solution for SAP"
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

  skin: solarized

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

# Access this webserver (WEBrick) from other computers on the LAN.
# For example, you can access this server from other computers at //hugo:4000
#
# If you get an error that port 4000 is already occupied, run
# "lsof -wni tcp:4000" to see which process used port 4000 and get the process PID.
# Then run "kill -9 <PID>" to kill the job.  
host: 0.0.0.0

# my site.variables
xssHmPage: '[**blueharbors.com/xss**](https://www.blueharbors.com/xss)'
